=== bendera/vscode-commit-message-editor/docs/schemas/config-v1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://bendera.github.com/vscode-commit-message-editor/schemas/config-v1.schema.json",
  "title": "Commit Message Editor configuration",
  "description": "Schema for VSCode Commit Message Editor extension shareable configuration",
  "type": "object",
  "properties": {
    "configVersion": {
      "type": "string"
    },
    "staticTemplate": {
      "$id": "#/properties/staticTemplate",
      "type": "array",
      "title": "Static template",
      "description": "Commit message template for the text view. Every line is an item in the array.",
      "default": [
        "feat: Short description",
        "",
        "Message body",
        "",
        "Message footer"
      ],
      "items": {
        "type": "string",
        "$id": "#/properties/staticTemplate/line"
      }
    },
    "dynamicTemplate": {
      "$id": "#/properties/dynamicTemplate",
      "type": "array",
      "title": "Dynamic template",
      "description": "Commit message template for the form view. Every line is an item in the array. Tokens are enclosed in curly brackets.",
      "default": [
        "{type}{scope}: {description}",
        "",
        "{body}",
        "",
        "{breaking_change}{footer}"
      ],
      "items": {
        "type": "string",
        "$id": "#/properties/dynamicTemplate/line"
      }
    },
    "tokens": {
      "$id": "#/properties/tokens",
      "type": "array",
      "title": "Tokens",
      "description": "Define form widgets for the form view.",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "$id": "#/properties/tokens/label",
            "type": "string",
            "title": "Token label",
            "description": "The visible label of the token in the form view."
          },
          "name": {
            "$id": "#/properties/tokens/name",
            "type": "string",
            "title": "Token name",
            "description": "The template variable name in the dynamic template."
          },
          "type": {
            "$id": "#/properties/tokens/type",
            "type": "string",
            "enum": [
              "enum",
              "text",
              "boolean"
            ],
            "title": "Token type",
            "description": "The token type determines what kind of form widget is displayed in the form. Enum: select dropdown, text: textfield or textarea, boolean: checkbox.",
            "default": "text"
          },
          "description": {
            "$id": "#/properties/tokens/description",
            "type": "string",
            "title": "Description",
            "description": "Helper text for the token."
          },
          "prefix": {
            "$id": "#/properties/tokens/prefix",
            "type": "string",
            "title": "Prefix",
            "description": "A text that will be prepended to the value if the value is not empty."
          },
          "suffix": {
            "$id": "#/properties/tokens/suffix",
            "type": "string",
            "title": "Suffix",
            "description": "A text that will be appended to the value if the value is not empty."
          },
          "multiline": {
            "type": "boolean"
          },
          "lines": {
            "type": "number"
          },
          "maxLines": {
            "type": "number"
          },
          "maxLength": {
            "type": "number"
          },
          "multiple": {
            "type": "boolean"
          },
          "separator": {
            "type": "string"
          },
          "combobox": {
            "type": "boolean"
          },
          "options": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "description": "The visible representation of the option. If the value is not defined the label will be the value."
                },
                "value": {
                  "type": "string",
                  "description": "The value of the option. If it's not defined the value will be the label."
                },
                "description": {
                  "type": "string",
                  "description": "Helper text for the option."
                }
              },
              "required": [
                "label"
              ]
            }
          }
        },
        "required": [
          "label",
          "name"
        ]
      }
    }
  },
  "required": [
    "configVersion",
    "staticTemplate",
    "dynamicTemplate",
    "tokens"
  ]
}

=== bendera/vscode-commit-message-editor/example-configs/gitmojis_zh-CN.json
{
  "$schema": "https://bendera.github.io/vscode-commit-message-editor/schemas/config-v1.schema.json",
  "configVersion": "1",
  "staticTemplate": [
    "feat: Short description",
    "",
    "Message body",
    "",
    "Message footer"
  ],
  "dynamicTemplate": [
    "{type}{scope}: {description}",
    "",
    "{body}",
    "",
    "{breaking_change}{footer}"
  ],
  "tokens": [
    {
      "label": "Type",
      "name": "type",
      "type": "enum",
      "combobox": true,
      "options": [
        {
          "label": "🩹 adhesive-bandage",
          "value": "🩹",
          "description": "简单修复非关键性问题"
        },
        {
          "label": "⚗ alembic",
          "value": "⚗",
          "description": "试验新功能"
        },
        {
          "label": "👽 alien",
          "value": "👽",
          "description": "由于外部API变化而更新代码"
        },
        {
          "label": "🚑 ambulance",
          "value": "🚑",
          "description": "紧急热修复"
        },
        {
          "label": "💫 animation",
          "value": "💫",
          "description": "新增或更新动画和过场"
        },
        {
          "label": "⬇️ arrow-down",
          "value": "⬇️",
          "description": "降级依赖版本"
        },
        {
          "label": "⬆️ arrow-up",
          "value": "⬆️",
          "description": "升级依赖版本"
        },
        {
          "label": "🎨 art",
          "value": "🎨",
          "description": "改进项目结构/代码格式"
        },
        {
          "label": "🍻 beers",
          "value": "🍻",
          "description": "醉醺醺的写代码"
        },
        {
          "label": "🍱 bento",
          "value": "🍱",
          "description": "新增或更新资源"
        },
        {
          "label": "🔖 bookmark",
          "value": "🔖",
          "description": "标签"
        },
        {
          "label": "💥 boom",
          "value": "💥",
          "description": "引入重大改变"
        },
        {
          "label": "🐛 bug",
          "value": "🐛",
          "description": "修复 BUG"
        },
        {
          "label": "🏗 building-construction",
          "value": "🏗",
          "description": "进行架构更改"
        },
        {
          "label": "💡 bulb",
          "value": "💡",
          "description": "在源代码中添加或更新注释"
        },
        {
          "label": "👥 busts-in-silhouette",
          "value": "👥",
          "description": "新增或更新贡献者"
        },
        {
          "label": "📸 camera-flash",
          "value": "📸",
          "description": "新增或更新快照"
        },
        {
          "label": "🗃 card-file-box",
          "value": "🗃",
          "description": "执行与数据库相关的更改"
        },
        {
          "label": "📈 chart-with-upwards-trend",
          "value": "📈",
          "description": "新增或更新分析或跟踪代码"
        },
        {
          "label": "🚸 children-crossing",
          "value": "🚸",
          "description": "提高用户体验 / 可用性"
        },
        {
          "label": "🤡 clown-face",
          "value": "🤡",
          "description": "进行 mock 测试"
        },
        {
          "label": "⚰️ coffin",
          "value": "⚰️",
          "description": "删除无效代码"
        },
        {
          "label": "🚧 construction",
          "value": "🚧",
          "description": "进行中的工作"
        },
        {
          "label": "👷 construction-worker",
          "value": "👷",
          "description": "新增或更新 CI 构建系统"
        },
        {
          "label": "🥚 egg",
          "value": "🥚",
          "description": "新增或更新一个彩蛋"
        },
        {
          "label": "🔥 fire",
          "value": "🔥",
          "description": "删除代码或文件"
        },
        {
          "label": "🌐 globe-with-meridians",
          "value": "🌐",
          "description": "国际化和本地化"
        },
        {
          "label": "🥅 goal-net",
          "value": "🥅",
          "description": "捕获异常"
        },
        {
          "label": "💚 green-heart",
          "value": "💚",
          "description": "修复 CI 构建"
        },
        {
          "label": "🔨 hammer",
          "value": "🔨",
          "description": "新增或更新开发脚本"
        },
        {
          "label": "➖ heavy-minus-sign",
          "value": "➖",
          "description": "移除依赖"
        },
        {
          "label": "➕ heavy-plus-sign",
          "value": "➕",
          "description": "添加依赖"
        },
        {
          "label": "📱 iphone",
          "value": "📱",
          "description": "响应式设计的工作"
        },
        {
          "label": "🏷️ label",
          "value": "🏷️",
          "description": "新增或更新类型"
        },
        {
          "label": "💄 lipstick",
          "value": "💄",
          "description": "新增或更新 UI 样式文件"
        },
        {
          "label": "🔒 lock",
          "value": "🔒",
          "description": "修复安全问题"
        },
        {
          "label": "🔊 loud-sound",
          "value": "🔊",
          "description": "新增或更新日志"
        },
        {
          "label": "🔍 mag",
          "value": "🔍",
          "description": "改善 SEO"
        },
        {
          "label": "📝 memo",
          "value": "📝",
          "description": "添加或更新文件"
        },
        {
          "label": "🧐 monocle-face",
          "value": "🧐",
          "description": "数据探索 / 数据巡检"
        },
        {
          "label": "🔇 mute",
          "value": "🔇",
          "description": "删除日志"
        },
        {
          "label": "📦 package",
          "value": "📦",
          "description": "新增或更新已编译的文件或包"
        },
        {
          "label": "📄 page-facing-up",
          "value": "📄",
          "description": "新增或更新 License"
        },
        {
          "label": "🛂 passport-control",
          "value": "🛂",
          "description": "编写与授权、角色和权限有关的代码"
        },
        {
          "label": "✏️ pencil2",
          "value": "✏️",
          "description": "修复拼写错误"
        },
        {
          "label": "💩 poop",
          "value": "💩",
          "description": "写不好的代码，需要改进"
        },
        {
          "label": "📌 pushpin",
          "value": "📌",
          "description": "将依赖设定为指定版本"
        },
        {
          "label": "♻️ recycle",
          "value": "♻️",
          "description": "重构代码"
        },
        {
          "label": "⏪ rewind",
          "value": "⏪",
          "description": "还原修改"
        },
        {
          "label": "🚀 rocket",
          "value": "🚀",
          "description": "部署项目"
        },
        {
          "label": "🚨 rotating-light",
          "value": "🚨",
          "description": "修复编译器 / 链接器警告"
        },
        {
          "label": "🙈 see-no-evil",
          "value": "🙈",
          "description": "新增或更新 .gitignore 文件"
        },
        {
          "label": "🌱 seedling",
          "value": "🌱",
          "description": "新增或更新 SEED 文件"
        },
        {
          "label": "✨ sparkles",
          "value": "✨",
          "description": "引入新特性"
        },
        {
          "label": "💬 speech-balloon",
          "value": "💬",
          "description": "新增或更新文本和文字"
        },
        {
          "label": "🎉 tada",
          "value": "🎉",
          "description": "初次提交"
        },
        {
          "label": "🚩 triangular-flag-on-post",
          "value": "🚩",
          "description": "添加、更新或删除特性标志"
        },
        {
          "label": "🚚 truck",
          "value": "🚚",
          "description": "移动或重命名资源"
        },
        {
          "label": "🔀 twisted-rightwards-arrows",
          "value": "🔀",
          "description": "合并分支"
        },
        {
          "label": "🗑 wastebasket",
          "value": "🗑",
          "description": "需要清理的废弃代码"
        },
        {
          "label": "♿️ wheelchair",
          "value": "♿️",
          "description": "改善无障碍环境"
        },
        {
          "label": "✅ white-check-mark",
          "value": "✅",
          "description": "添加、更新或通过测试"
        },
        {
          "label": "🔧 wrench",
          "value": "🔧",
          "description": "新增或更新配置文件"
        },
        {
          "label": "⚡️ zap",
          "value": "⚡️",
          "description": "提高性能"
        }
      ],
      "description": "Type of changes"
    },
    {
      "label": "Scope",
      "name": "scope",
      "description": "A scope may be provided to a commit’s type, to provide additional contextual information and is contained within parenthesis, e.g., \"feat(parser): add ability to parse arrays\".",
      "type": "text",
      "multiline": false,
      "prefix": "(",
      "suffix": ")"
    },
    {
      "label": "Short description",
      "name": "description",
      "description": "Short description in the subject line.",
      "type": "text",
      "multiline": false
    },
    {
      "label": "Body",
      "name": "body",
      "description": "Optional body",
      "type": "text",
      "multiline": true,
      "lines": 5,
      "maxLines": 10
    },
    {
      "label": "Breaking change",
      "name": "breaking_change",
      "type": "boolean",
      "value": "BREAKING CHANGE: ",
      "default": false
    },
    {
      "label": "Footer",
      "name": "footer",
      "description": "Optional footer",
      "type": "text",
      "multiline": true
    }
  ]
}
